### ISSUE TITLE
No Notification received 

### ISSUE THREAD

**Issue by EmadSaad** [giovannyreyeso/NetFireBasePush#1]
Dear Giovanny,

I follow your steps to create a push notification and used firebase keys in their place at code but I didn't receive any notification on my App.
Kindly explain to me why? there is no notification received in my app.

Best Regards.

**Comment by giovannyreyeso** [comment]
Hi @EmadSaad , how are u?. You was try to send a push notification in firebase console?. You follow the steps for get token of the device?

If you try to send with firebase console and notification does not receive it the problem was other.

If you receive the notification from console. you will need debug the class
